name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Login to cycr
        uses: docker/login-action@v2
        with:
          registry: cycr.io
          username: ${{ secrets.CYCR_USER }}
          password: ${{ secrets.CYCR_KEY }}
      
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      
      - name: Build and push Docker image to Docker Hub
        uses: depot/build-push-action@v1
        with:
          context: .
          push: true
          tags: |
            docker.io/clysec/doh-server:latest
            ghcr.io/clysec/doh-server:latest
            cycr.io/clysec/doh-server:latest
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
 